server:
  port: 8880
  servlet:
    context-path: /cache

spring:
  application:
    name: cache
  ##Cache
  cache:
    #type: simple
    type: redis
  ##Redis
  redis:
    #单机模式
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 2000
    ssl: false
    url:
    #哨兵模式
    sentinel:
      master:
      nodes:
    #集群模式
    cluster:
      nodes:
      max-redirects:
