server:
  port: 18181
  servlet:
    context-path: /ent
#spring:
#  security:
#    user:
#      name: admin
#      password: 123
#      roles: ROLE_ADMIN
#    filter:
#      dispatcher-types:
#      order:
spring:
  datasource:
    name: blog
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1001
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


